set(COMPILER_OPTIONS)
set(LINKER_OPTIONS)

set(COMPILE_DEFINITIONS
	-D_WIN32 -D_WINDOWS -D_ALLOW_KEYWORD_MACROS -D__STDC_LIMIT_MACROS
	-D_CRT_SECURE_NO_WARNINGS=1 -D_CRT_SECURE_NO_DEPRECATE=1 -D_CRT_NONSTDC_NO_DEPRECATE=1
)

if(CMAKE_BUILD_TYPE STREQUAL "Release")
	set(COMPILER_OPTIONS
		${COMPILER_OPTIONS}
		/Zi
	)
endif()

set(COMPILER_OPTIONS
	${COMPILER_OPTIONS}
	/wd4819 /wd4828 /wd5033 /permissive- /utf-8 /wd4005 /MP
)

if(CMAKE_BUILD_TYPE STREQUAL "Release")
	set(LINKER_OPTIONS
		${LINKER_OPTIONS}
		/OPT:REF
		/OPT:ICF
	)
endif()
