# Logger
# Copyright (C) 2023-2024 Wend4r
# Licensed under the GPLv3 license. See LICENSE file in the project root for details.

set(PLATFORM_COMPILE_DEFINITIONS
	${PLATFORM_COMPILE_DEFINITIONS}

	_WIN32 _WINDOWS
	_ALLOW_KEYWORD_MACROS __STDC_LIMIT_MACROS
	_CRT_SECURE_NO_WARNINGS=1 _CRT_SECURE_NO_DEPRECATE=1 _CRT_NONSTDC_NO_DEPRECATE=1
)

set(PLATFORM_COMPILE_OPTIONS
	${PLATFORM_COMPILE_OPTIONS}

	/wd4005 /wd4819 /wd4828 /wd5033
	/permissive- /utf-8 /MP
)

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
	set(PLATFORM_LINK_OPTIONS
		${PLATFORM_LINK_OPTIONS}

		/NODEFAULTLIB:libcmt
	)
endif()
